"""initial_schema

Revision ID: 9f42c2b69d95
Revises: 
Create Date: 2026-02-20 10:01:18.541794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f42c2b69d95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_comment_like', 'comment_like', ['comment_id', 'user_id'])
    op.drop_column('user', 'title_color')
    op.create_unique_constraint('unique_user_relation', 'user_relation', ['from_user_id', 'to_user_id', 'relation_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_relation', 'user_relation', type_='unique')
    op.add_column('user', sa.Column('title_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('unique_comment_like', 'comment_like', type_='unique')
    # ### end Alembic commands ###
